# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: malilib

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@master
      with:
        java-version: 1.8
    - name: getsource
      run: git clone --recursive -b fabric_1.15.2 https://github.com/maruohon/malilib.git malilib
    - name: Build with Gradle
      run: |
        cd malilib
        chmod +x gradlew
        ./gradlew build
    - name: upload jar
      uses: actions/upload-artifact@master
      with:
        name: mods
        path: malilib/build/libs
